[package]
name = "jadevid"
description = "A video editor...I'm trying again...Maybe I'll get somewhere :shrug:"
version = "0.1.0"
edition = "2024"
publish = false
build = "build.rs"
authors = ["CJ Burkey <bulletlanguage@gmail.com>"]

[dependencies]
slint = "1.9.2"
ffmpeg-next = "7.1.0"
smol = "2.0.0"
anyhow = "1.0"
futures = "0.3.28"
cpal = "0.15.2"
ringbuf = "0.3.3"
bytemuck = "1.13.1"
derive_more = "1"

[build-dependencies]
slint-build = "1.9.2"
